export const AppName = 'Vidya'
export * from './content'
export * from './identity'
export * from './lifecycle'
export * from './schoolCode'
export * from './permissions'
export * from './ports'
export * from './preferredTimes'
export * from './sync'
