#!/bin/sh
set -eu

: "${VIDYA_GATEWAY_TLS_ENABLED:=false}"
: "${VIDYA_GATEWAY_API_UPSTREAM:=http://host.docker.internal:7810}"
: "${VIDYA_GATEWAY_ADMIN_UPSTREAM:=http://host.docker.internal:7811}"
: "${VIDYA_GATEWAY_DOMAIN:=}"
: "${VIDYA_GATEWAY_HSTS_MAX_AGE:=63072000}"
: "${VIDYA_GATEWAY_RATE_LIMIT_RPS:=20}"
: "${VIDYA_GATEWAY_RATE_LIMIT_BURST:=40}"

VIDYA_GATEWAY_HSTS_DIRECTIVE=

if [ "$VIDYA_GATEWAY_TLS_ENABLED" = "true" ]; then
  if [ -z "$VIDYA_GATEWAY_DOMAIN" ]; then
    echo "gateway: VIDYA_GATEWAY_TLS_ENABLED=true but VIDYA_GATEWAY_DOMAIN is not set" >&2
    echo "gateway: see README.md, 'TLS certificates', for what a deployment must set" >&2
    exit 1
  fi

  VIDYA_GATEWAY_SITE_ADDRESS="$VIDYA_GATEWAY_DOMAIN"
  VIDYA_GATEWAY_HSTS_DIRECTIVE="header Strict-Transport-Security \"max-age=${VIDYA_GATEWAY_HSTS_MAX_AGE}; includeSubDomains\""
else
  VIDYA_GATEWAY_SITE_ADDRESS=":8080"
fi

VIDYA_GATEWAY_RATE_LIMIT_SUSTAINED_EVENTS=$((VIDYA_GATEWAY_RATE_LIMIT_RPS * 5))

export VIDYA_GATEWAY_API_UPSTREAM VIDYA_GATEWAY_ADMIN_UPSTREAM VIDYA_GATEWAY_SITE_ADDRESS VIDYA_GATEWAY_HSTS_DIRECTIVE \
  VIDYA_GATEWAY_RATE_LIMIT_RPS VIDYA_GATEWAY_RATE_LIMIT_BURST VIDYA_GATEWAY_RATE_LIMIT_SUSTAINED_EVENTS

exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
