// Public API of the edit-lesson-content feature — editing sections and blocks. Owned by T5.
export { getLessonVersion, saveLessonVersion } from './api'
export { useMenuKeys } from './lib'
export type { BlockFault } from './model'
export {
  addAnswer,
  addBlock,
  addSection,
  blockBelow,
  checkBlockUrl,
  contentProblems,
  convertBlock,
  createBlock,
  duplicateBlock,
  EmbedHosts,
  embedSrc,
  endTextBlock,
  findBlockFaults,
  findInvalidBlocks,
  insertBlockAfter,
  insertSectionAfter,
  isEmbedSource,
  isKnownBlockType,
  mediaSrc,
  moveBlock,
  moveSection,
  newBlockId,
  newSectionId,
  pruneForSave,
  removeAnswer,
  removeBlock,
  removeSection,
  renameSection,
  reorderBlocks,
  reorderSections,
  sectionBelow,
  setAnswer,
  setQuestion,
  setRightAnswer,
  setSectionAssessment,
  updateBlock,
  useLessonContentEditor,
} from './model'
export type * from './types'
export { AuthorableSources, BlockTypes } from './types'
export {
  AudioBlockEditor,
  BlockHandle,
  BlockInserter,
  BlockInsertMenu,
  BlockMenu,
  LessonBlockEditor,
  LessonBlockFrame,
  MarkdownText,
  QuizBlockEditor,
  TextBlockEditor,
  useMarkdownEditor,
  VideoBlockEditor,
} from './ui'
export type * from './ui/types'
