// Public API of the edit-lesson-content feature — editing sections and blocks. Owned by T5.
export { getLessonVersion, saveLessonVersion } from './api'
export type { BlockFault } from './model'
export {
  addAnswer,
  addBlock,
  addSection,
  blockBelow,
  blockFaults,
  checkBlockUrl,
  contentProblems,
  createBlock,
  duplicateBlock,
  EmbedHosts,
  embedSrc,
  insertBlockAfter,
  invalidBlocks,
  isEmbedSource,
  isKnownBlockType,
  mediaSrc,
  moveBlock,
  moveSection,
  newBlockId,
  newSectionId,
  prunedForSave,
  removeAnswer,
  removeBlock,
  removeSection,
  renameSection,
  renderMarkdown,
  reorderBlocks,
  reorderSections,
  setAnswer,
  setQuestion,
  setRightAnswer,
  setSectionAssessment,
  updateBlock,
  useLessonContentEditor,
} from './model'
export type * from './types'
export { AuthorableSources, BlockTypes } from './types'
export {
  AudioBlockEditor,
  BlockHandle,
  BlockInserter,
  BlockInsertMenu,
  BlockMenu,
  LessonBlockEditor,
  LessonBlockFrame,
  MarkdownText,
  QuizBlockEditor,
  TextBlockEditor,
  useMarkdownEditor,
  VideoBlockEditor,
} from './ui'
export type * from './ui/types'
